

development:
  adapter: mysql
  database: schedule_dev
  username: root
  password:  
  host: localhost

test:
  adapter: mysql
  database: schedule_test
  username: root
  password:  
  host: localhost
